FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app
COPY EnnumEzutthum.csproj EnnumEzutthum.csproj
RUN dotnet restore EnnumEzutthum.csproj
COPY . .
RUN dotnet publish -c Release -o /output --no-restore --nologo