name: sramaswami11-blazor-wasm
static_sites:
- name: relizealous
  github:
    repo: sramaswami11/Relizealous
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.build 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html